---
# http is required when running the development server
baseurl: "http://www.dynomitedb.com"
#baseurl: "//www.dynomitedb.com"
languageCode: "en-us"
title: "DynomiteDB - A high performance, linearly scalable, highly available (HA) and distributed database"
buildDrafts: "false"
buildFuture: "false"
metaDataFormat: "yaml"
publishdir: "public" # Change this to "../"
theme: "dynomite"
googleAnalytics: "UA-76466336-1"

permalinks:
  # Optional. Change the permalink format for the 'blog' content type.
  blog: "/blog/:year/:month/:day/:title/"

params:
  product: "DynomiteDB"
  description: "DynomiteDB is a high performance, linearly scalable, highly available (HA) and distributed database."
  keywords: "dynomite, cache, high availability, HA, linearly scalable, scalable, distributed, distributed database"
  languagecode: "en-US"
  author: "DynomiteDB"
  copyright: "2016 DynomiteDB.com"

  # Social links are displayed in the footer
  twitter: "https://twitter.com/DynomiteDB"
  github: "https://github.com/DynomiteDB"
  #facebook: "https://www.facebook.com/<username>"
  #delicious: "https://delicious.com/<username>"
  #linkedin: "https://www.linkedin.com/in/<username>"
  #flickr: "https://www.flickr.com/photos/<username>"

  # show default summaries on the frontpage or not
  use_summaries: false

  # Documentation
  current_dyno_version: "v1.3.1"
  current_dynomite_version: "v0.5.6"
  current_dynomite_manager_version: "v1.0.2"

  strings:
    # name of the header used in the post list page
    # Used in:
    # ./src/themes/dynomite/layouts/_default/list.html
    # ./src/themes/dynomite/layouts/partials/header.html
    #posts_list_header: "Posts"

    # used date format
    date_format: 'Jan 2, 2006'

    blog_list_header: "Blog"

  theme:
    inverse: false   # if true, use inverse colors
    name: "flatly"   # Bootswatch theme
    # name must be one of:
    # name: cerulean, cosmo, cyborg, default, flatly, journal, lumen, paper,
    #        readable, sandstone, simplex, slate, spacelabs, superhero, united,
    #        yeti
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Manual"
      url: "/manual"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "7.5"
    versions:
      - "latest"
      - "7.4"
      - "7.3"
      - "7.2"
      - "7.1"
      - "7.0"
      - "develop"
  docs:
    - id: "dynomite"
      name: "Dynomite"
      version: "v0.5.6"
    - id: "dynomite-manager"
      name: "Dynomite Manager"
      version: "v1.0.2"
    - id: "dyno-java"
      name: "Dyno Client (Java)"
      version: "v1.3.1"

menu:
  main:
      - Name: "Docs"
        Weight: -110
        Identifier: "docs"
        URL: "/docs/"
      - Name: "Blog"
        Weight: -100
        Identifier: "blog"
        URL: "/blog/"
      - Name: "FAQ"
        Weight: -90
        Identifier: "faq"
        URL: "/faq/"
#      - Name: "Why DynomiteDB"
#        Weight: -80
#        Identifier: "why"
#        URL: "/why-dynomitedb/"
      - Name: "Roadmap"
        Weight: -80
        Identifier: "roadmap"
        URL: "/roadmap/"

---
